@DocuWareWebHooks_HostAddress = http://localhost:5011

POST {{DocuWareWebHooks_HostAddress}}/webhooks/docuware
Accept: application/json
Content-Type: application/json
x-docuware-signature: 9e6c9922779a1b8ef4f8a2e968b80c99de323c8e493637bc39276678abf8f175d82ef99c12b8f179c5862e9ab90d75193de1b6109c33c308de93a87c4cedc161
{
 "DOCUMENT_TYPE": "Invoice In",
 "COMPANY_NAME": "STORAGE EXPERTS INC.",
 "COMPANY_NAME2": "STORAGE EXPERTS INC.",
 "COMPANY_STREET": null,
 "COMPANY_ZIP": null,
 "COMPANY_CITY": null,
 "COMPANY_STATE": null,
 "COMPANY_PHONE": null,
 "COMPANY_EMAIL": null,
 "COMPANY_WEBSITE": null,
 "COMPANY_NUMBER": "1",
 "COMPANY_ACCOUNT": null,
 "DOCUMENT_NUMBER": "126496836",
 "DOCUMENT_DATE": "2022-12-20T00:00:00",
 "DUE_DATE": "2022-12-20T00:00:00",
 "COST_CENTER": null,
 "ORDER_NUMBER": null,
 "INVOICE_NUMBER": null,
 "DELIVERY_NOTE_NUMBER": null,
 "STORED_ON": "2023-07-12T00:00:00",
 "STORED_BY": "chris.gritton.admin",
 "LAST_ACCESS_ON": "2023-07-12T00:00:00",
 "LAST_ACCESS_BY": "chris.gritton.admin",
 "LAST_MODIFICATION_ON": "2023-07-12T00:00:00",
 "LAST_MODIFICATION_BY": "chris.gritton.admin",
 "ORDER_NUMBER1": "1154967",
 "STATUS": "For Approval",
 "DOCUMENT_YEAR": "2022",
 "DOCUMENT_MONTH": "Dec",
 "GL_COSTCENTER_GROUPS": null,
 "GL_DONE": null,
 "DOCUMENT_LINK": "/DocuWare/Platform/Webclient/Integration?fc=&p=V&did=16",
 "VALIDATIONSTATUS": null,
 "PROCESS_AND_DURATION": {"UpdateStatus":null,"Values":["IP - 1 Validation: 1 Minute(s)"],"currentTag":0,"IgnoreInvalidEnums":false},
 "PROCESS_STATUS": "EXPORTED",
 "INVOICE_DURATION": "1 Minute(s)",
 "REQUESTOR": null,
 "PO_UPDATE": null,
 "PO_VALUE_UPDATE": null,
 "REASON": null,
 "PAYMENT_DETAILS": null,
 "PAYMENT_METHOD": null,
 "PAYMENT_DATE": null,
 "SUBSIDIARY_NAME": "Subsidiary 1",
 "COSTCENTER_NUMBER": null,
 "COMPANY_NUMBER_LIST": null,
 "ACCOUNTING_PERIOD": null,
 "GL_PREFILL_OPTION": null,
 "SUBSIDIARY_NUMBER": null,
 "E_ONE_STATUS": null,
 "E_ONE_MESSAGE": null,
 "E_ONE_EXTERNAL_ID": null,
 "QB_VENDOR_ID": "Alpha Beta",
 "QB_ACCOUNT_ID": "33",
 "QB_TRANSACTION_DATE": "2025-06-26T00:00:00",
 "DWEXTENSION": ".pdf",
 "DWDOCID": 80,
 "DWSECTIONCOUNT": 1,
 "DWSTOREDATETIME": "2023-11-21T17:37:21",
 "DWSTOREUSER": "USER1"
}

###
